#Q1) Write a program to take a number as input and convert it into its binary equivalent.
number=int(input("Enter the value:"))#User enters number to be converted to binary.
r=1 #initialize r.
b=0 #initialize b.
#Use while loop to convert the number to binary.
while number>0:
    a=number%2
    b=r*a+b
    r=r*10
    number=number//2
print("The binary equivalent of value is:",b)

#Q2) Write an interactive Python calculator program. The program should allow the user to type a mathematical expression, and then print the value of the expression.

x="Yes"
while x=="yes" or x=="Yes": #Condition for loop to work.
    a=int(input("\nEnter value 1: ")) #User enters values to be calculated
    b=int(input("Enter value 2: "))
    c=input("Enter the desired mathematical expression( '+' or '-' or '*' or '/' ): ")
    if c=="+": #for addition.
       output=a+b
       print(a," + ",b," = ",output)
    elif c=="-": #for subtraction.
       output=a-b
       print(a," - ",b," = ",output)
    elif c=="*": #for multiplication.
       output=a*b
       print(a," * ",b," = ",output)
    elif c=="/": #for division.
       output=a/b
       print(a," / ",b," = ",output)
    else:
       print("Invalid Input") #If user enters non valid value.
    x=input("Do you want to continue?(yes/no)") #value to iterate the staements.

#Q3) Translate each of the following mathematical expression into a equivalent python expression.
import math #calling math library 
#a)
exp=(3+4)*5
print("\n a)The value is= ",exp)
#b)
n=int(input("\nEnter value for n: "))
exp=(n-1)*n/2
print("\n b)The value is= ",exp)
#c)
r=int(input("\nEnter value for r: "))
new_var = math.pi
exp=4*(r**2)*new_var
print("\n c)The value is= ",exp)
#d)
r=int(input("\nEnter value of r: "))
a=int(input("Enter value of a: "))
b=int(input("Enter value of b: "))
exp=math.sqrt((r*(math.sin(a))**2)+(r*(math.cos(a))**2))
print("\n d)The value is= ",exp)
#e
x1=int(input("\nEnter value of x1: "))
x2=int(input("Enter value of x2: "))
y1=int(input("Enter value of y1: "))
y2=int(input("Enter value of y2: "))
if x1==x2:
    print("Not possible")
else:
    exp=(y2-y1)/(x2-x1)
    print("\n e)The value is= ",exp)


#Q4)Show the sequence of numbers that would be generated by each of the following range expressions.
#a
print("\n a)")
for i in range(5):
    print(i,end=" ")
#b
print("\n b)")
for i in range(3,10):
    print(i,end=" ")
#c
print("\n c)")
for i in range(4,13,3):
    print(i,end=" ")    
#d
print("\n d)")
for i in range(15,5,-2):
    print(i,end=" ")
#e
print("\n e)")
for i in range(5,3):
    print(i,end=" ")

#Q5)Write a program that computes the weight of a carbohydrate.
wt_c=12.0107 #Given weight of carbon.
wt_h=1.00794 #Given weight of hydrogen.
wt_o=15.9994 #Given weight of oxygen.
h=int(input("\nNo of hydorgen atom:"))
o=int(input("No of oxygen atom:"))
c=int(input("No of carbon atom"))
t_wt=(h*wt_h + c*wt_c + o*wt_o) #total weight.
print("\nThe total weight of the molecule is", t_wt)




   
